Suggestions
Dheeraj-Thikkamaneni/NLP-Spell-Check pull request #25
Opened 2021-11-16 06:19 UTC by Dheeraj-Thikkamaneni

find suggestions and show top five suggestions in UI

2021-11-16 06:29 UTC, shirishma1 requested changes
can we adjust the spacing of extra lines in the code

2021-11-16 06:31 UTC, Dheeraj-Thikkamaneni commented
> can we adjust the spacing of extra lines in the code

2021-11-16 06:36 UTC, Dheeraj-Thikkamaneni commented
> can we adjust the spacing of extra lines in the code

yeah, sure will do, its just my habit for my personnel ease for readability

2021-11-16 06:40 UTC, merged

2021-11-17 04:21 UTC, gantlavamshikrishnareddy commented on spellcheck.py
> +    for i in range(1, 15):
why have you used less amount of data for English than Irish? would you think the frequency list would be good for the data given to training for English and contain all words?